function GROUND_TYPE () { }
GROUND_TYPE.CRILE_LEFT = 1;
GROUND_TYPE.CRILE_CENTER = 2;
GROUND_TYPE.CRILE_RIGHT = 3;

GROUND_TYPE.RECT_LEFT = 4;
GROUND_TYPE.RECT_CENTER = 5;
GROUND_TYPE.RECT_RiGHT = 6;
